// The v0.9 vocabulary #206 added to `crates/triton-core/src/a2ui/v09.rs`,
// asserted against envelopes a **real** Triton process actually produced.
//
// The fixtures under `test/fixtures/` are generated by
// `crates/triton-tests/tests/a2ui_flutter_fixtures.rs` — FakeAgent returns a
// surface, a real gateway wraps it at the negotiated v0.9, the response body
// lands on disk. That Rust test re-produces them on every CI run and fails if
// the checked-in copy has drifted, so these widget tests cannot quietly assert
// against a wire shape Triton stopped emitting. A hand-written Dart literal is
// exactly how the `kind`/`type` mismatch survived for weeks: both sides agreed
// with themselves.
//
// Each degrade below is asserted with a positive control, because "the field
// was dropped" and "the field was handled" look identical from a `findsNothing`.

import 'dart:convert';
import 'dart:io';

import 'package:a2ui_flutter/a2ui_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

Map<String, dynamic> fixture(String name) =>
    jsonDecode(File('test/fixtures/$name.json').readAsStringSync())
        as Map<String, dynamic>;

List<Map<String, dynamic>> streamOf(Map<String, dynamic> envelope) =>
    (envelope['stream'] as List)
        .map((e) => (e as Map).cast<String, dynamic>())
        .toList();

Future<void> pump(
  WidgetTester tester,
  Map<String, dynamic> envelope, {
  void Function(String, Map<String, dynamic>)? onAction,
  A2uiResourceActionCallback? onResourceAction,
}) async {
  await tester.pumpWidget(MaterialApp(
    home: Scaffold(
      body: SingleChildScrollView(
        child: A2UIRenderer(
          envelope: envelope,
          onAction: onAction,
          onResourceAction: onResourceAction,
        ),
      ),
    ),
  ));
  await tester.pump();
}

Color? background(WidgetTester tester, String label) => tester
    .widget<FilledButton>(find.widgetWithText(FilledButton, label))
    .style
    ?.backgroundColor
    ?.resolve(const <WidgetState>{});

void main() {
  // ---------------------------------------------------------------
  // The fixtures themselves. If a fixture stopped carrying the field
  // a test below is about, that test would pass vacuously — so pin
  // the input before pinning the behaviour.
  // ---------------------------------------------------------------
  group('the produced fixtures carry what the tests are about', () {
    test('the extended envelope has every field #206 added', () {
      final s = streamOf(fixture('v09_extended'));
      expect(s[0]['pills'], {'hoffmann': 'Hoffmann Automotive'});
      expect((s[0]['text'] as String).contains('[[customer::secret]]'), isTrue);
      expect(s[1]['primary'], true);
      final fields = (s[3]['fields'] as List).cast<Map>();
      expect(fields[0]['placeholder'], 'e.g. 30d');
      expect(fields[0]['default'], '30d');
      expect(fields[3].containsKey('default'), isFalse);
      expect(s[4]['title'], 'Renewals');
      expect(s[4]['series'], [4.0, 8.0, 6.0]);
      expect(
        streamOf(fixture('v09_resource_button'))[1]['resource'],
        'ui://peacock/report/renewals?window=90d',
      );
    });

    test('the pre-#206 envelope has none of them', () {
      final s = streamOf(fixture('v09_pre206'));
      expect(s[0].containsKey('pills'), isFalse);
      expect(s[1].containsKey('primary'), isFalse);
      expect(s[1].containsKey('resource'), isFalse);
      for (final f in (s[2]['fields'] as List).cast<Map>()) {
        expect(f.containsKey('placeholder'), isFalse);
        expect(f.containsKey('default'), isFalse);
      }
      expect(s[3].containsKey('title'), isFalse);
      expect(s[3].containsKey('series'), isFalse);
    });
  });

  // ---------------------------------------------------------------
  // text.pills — the D27 label degrade
  // ---------------------------------------------------------------
  group('text.pills', () {
    testWidgets('a resolved wikilink renders its label, an unresolved one the '
        'bare id — and neither leaks raw syntax', (tester) async {
      await pump(tester, fixture('v09_extended'));

      // Resolved: the pill map supplied a display name.
      expect(find.text('Hoffmann Automotive'), findsOneWidget);
      // Unresolved (D27: the caller may not read that instance, so the id has
      // no entry). This is the assertion the whole field exists for — and it
      // is a POSITIVE one: "renders the bare id" must be distinguishable from
      // "renders nothing", which a findsNothing could never tell apart.
      expect(find.text('secret'), findsOneWidget);
      // Neither reaches the reader as `[[…]]`.
      expect(
        find.textContaining('[[', findRichText: true),
        findsNothing,
      );
      expect(
        find.textContaining('customer::', findRichText: true),
        findsNothing,
      );
    });

    testWidgets('an envelope with no pills map still resolves to bare ids',
        (tester) async {
      // The worst D27 case: the caller may read NONE of the referenced
      // instances, so the map is empty and the wire omits it entirely. If the
      // renderer only handled wikilinks when a map is present, that case would
      // leak raw syntax at exactly the moment it matters most.
      await pump(tester, fixture('v09_pre206'));
      expect(find.text('hoffmann'), findsOneWidget);
      expect(find.textContaining('[[', findRichText: true), findsNothing);
    });

    testWidgets('v0.8 is left alone — its text still renders verbatim',
        (tester) async {
      // ADR-4 / #205: the trees are separate contracts. v0.8 has no `pills`,
      // so it must keep the rendering it has, brackets and all.
      await tester.pumpWidget(const MaterialApp(
        home: Scaffold(
          body: A2UIv08Renderer(envelope: {
            'stream': [
              {
                'Component': {
                  'Text': {'text': 'See [[customer::hoffmann]]'},
                },
              },
            ],
          }),
        ),
      ));
      expect(
        find.textContaining('[[customer::hoffmann]]', findRichText: true),
        findsOneWidget,
      );
    });
  });

  // ---------------------------------------------------------------
  // form.fields[].placeholder / .default
  // ---------------------------------------------------------------
  group('form defaults', () {
    testWidgets('an untouched form submits the agent\'s proposal',
        (tester) async {
      Map<String, dynamic>? values;
      await pump(tester, fixture('v09_extended'),
          onAction: (tool, v) => values = v);
      await tester.tap(find.widgetWithText(FilledButton, 'Run'));
      await tester.pump();
      expect(values?['window'], '30d');
      expect(values?['limit'], 25);
      expect(values?['dry'], true);
      // The other half of the pair: a placeholder is hint text, not a value.
      // A placeholder that submitted itself would put words the agent never
      // proposed into a record a consultant signed off.
      expect(values!.containsKey('note'), isFalse);
    });

    testWidgets('a default is editable — typing wins over the proposal',
        (tester) async {
      Map<String, dynamic>? values;
      await pump(tester, fixture('v09_extended'),
          onAction: (tool, v) => values = v);
      // Positive control that the default is seeded into the *field*, not just
      // into the submit map: it is there to be read and overwritten.
      expect(
        tester.widget<TextField>(find.byType(TextField).first).controller?.text,
        '30d',
      );
      await tester.enterText(find.byType(TextField).first, '7d');
      await tester.tap(find.widgetWithText(FilledButton, 'Run'));
      await tester.pump();
      expect(values?['window'], '7d');
    });

    testWidgets('placeholders reach the field as hint text', (tester) async {
      await pump(tester, fixture('v09_extended'));
      final hints = tester
          .widgetList<TextField>(find.byType(TextField))
          .map((t) => t.decoration?.hintText)
          .toList();
      expect(hints, contains('e.g. 30d'));
      expect(hints, contains('optional note'));
    });

    testWidgets('a pre-#206 form still submits only what was typed',
        (tester) async {
      // The backward-compatibility control. No `default` anywhere means the
      // untouched form must send nothing at all, exactly as it did before —
      // seeding an empty string would be a new, wrong value.
      Map<String, dynamic>? values;
      await pump(tester, fixture('v09_pre206'),
          onAction: (tool, v) => values = v);
      await tester.tap(find.widgetWithText(FilledButton, 'Run'));
      await tester.pump();
      expect(values, isEmpty);

      // Positive control: the same form does carry a typed value, so the
      // emptiness above is "nothing was proposed", not "submit is broken".
      await tester.enterText(find.byType(TextField).first, 'typed');
      await tester.tap(find.widgetWithText(FilledButton, 'Run'));
      await tester.pump();
      expect(values, {'window': 'typed'});
    });
  });

  // ---------------------------------------------------------------
  // button.primary
  // ---------------------------------------------------------------
  group('button.primary', () {
    testWidgets('the primary action is weighted above its siblings',
        (tester) async {
      await pump(tester, fixture('v09_extended'), onAction: (_, _) {});
      final scheme = ThemeData().colorScheme;
      expect(background(tester, 'Approve'), scheme.primary);
      // Positive control: the sibling rendered too, and kept the tonal
      // weighting every button had before — so "primary" is a contrast, not a
      // global restyle.
      expect(background(tester, 'Reject'), scheme.tertiaryContainer);
    });

    testWidgets('a pre-#206 button keeps the tonal weighting', (tester) async {
      await pump(tester, fixture('v09_pre206'), onAction: (_, _) {});
      final scheme = ThemeData().colorScheme;
      expect(background(tester, 'Approve'), scheme.tertiaryContainer);
    });
  });

  // ---------------------------------------------------------------
  // report inline preview
  // ---------------------------------------------------------------
  group('report inline preview', () {
    testWidgets('a preview-bearing report draws the preview and keeps the '
        'dispatch control', (tester) async {
      final calls = <(String, Map<String, dynamic>)>[];
      await pump(tester, fixture('v09_extended'),
          onAction: (t, a) => calls.add((t, a)));
      // The preview a host that cannot dispatch `render_report` shows instead.
      expect(find.text('Renewals'), findsOneWidget);
      expect(find.text('Q1'), findsOneWidget);
      expect(find.text('Q3'), findsOneWidget);
      // …carried BESIDE report_id, not instead of it: a host that can dispatch
      // still can. That is the whole degradation contract.
      await tester.ensureVisible(find.text('Open report: renewals'));
      await tester.pump();
      await tester.tap(find.text('Open report: renewals'));
      await tester.pump();
      expect(calls.single.$1, 'render_report');
      expect(calls.single.$2['report_id'], 'renewals');
    });

    testWidgets('a host that cannot dispatch still sees the preview',
        (tester) async {
      await pump(tester, fixture('v09_extended'));
      expect(find.text('Renewals'), findsOneWidget);
      expect(find.text('Q2'), findsOneWidget);
      // Positive control: without an action sink there is no dispatch control
      // at all, so the preview is the only thing carrying the report.
      expect(find.text('Open report: renewals'), findsNothing);
    });

    testWidgets('a pre-#206 report is unchanged: an open control, no preview',
        (tester) async {
      final calls = <(String, Map<String, dynamic>)>[];
      await pump(tester, fixture('v09_pre206'),
          onAction: (t, a) => calls.add((t, a)));
      expect(find.text('Open report: renewals'), findsOneWidget);
      expect(find.text('Renewals'), findsNothing);
      await tester.tap(find.text('Open report: renewals'));
      await tester.pump();
      expect(calls.single.$1, 'render_report');
      expect(calls.single.$2, {'window': '90d', 'report_id': 'renewals'});
    });
  });

  // ---------------------------------------------------------------
  // button.resource
  // ---------------------------------------------------------------
  group('button.resource', () {
    testWidgets('a resource-carrying button reaches onResourceAction whole',
        (tester) async {
      String? tool;
      Map<String, dynamic>? args;
      String? resource;
      var plainActions = 0;
      await pump(
        tester,
        fixture('v09_resource_button'),
        onAction: (_, _) => plainActions++,
        onResourceAction: (t, a, r) {
          tool = t;
          args = a;
          resource = r;
        },
      );
      await tester.tap(find.text('Open renewals'));
      await tester.pump();
      expect(resource, 'ui://peacock/report/renewals?window=90d');
      // The tool call rides along: a resource button is an action that also
      // names a view, not a link. A callback that only carried the uri would
      // lose the dispatch the same way `onAction` loses the resource.
      expect(tool, 'render_report');
      expect(args, {'report_id': 'renewals'});
      // …and it is routed once, not to both sinks.
      expect(plainActions, 0);
    });

    testWidgets('without onResourceAction the button behaves exactly as before',
        (tester) async {
      // The backward-compatibility control: a host that never heard of the new
      // callback (the Explorer) keeps the (tool, args) dispatch it has today.
      final calls = <(String, Map<String, dynamic>)>[];
      await pump(tester, fixture('v09_resource_button'),
          onAction: (t, a) => calls.add((t, a)));
      await tester.tap(find.text('Open renewals'));
      await tester.pump();
      expect(calls.single.$1, 'render_report');
      expect(calls.single.$2, {'report_id': 'renewals'});
    });

    testWidgets('a button with no resource never reaches onResourceAction',
        (tester) async {
      var resourceCalls = 0;
      final calls = <String>[];
      await pump(
        tester,
        fixture('v09_pre206'),
        onAction: (t, _) => calls.add(t),
        onResourceAction: (_, _, _) => resourceCalls++,
      );
      await tester.tap(find.text('Approve'));
      await tester.pump();
      expect(resourceCalls, 0);
      // Positive control: the tap landed somewhere — on the plain sink.
      expect(calls, ['heron_approve']);
    });
  });

  // ---------------------------------------------------------------
  // the unknown-kind degrade
  // ---------------------------------------------------------------
  group('unknown kinds', () {
    const unknown = {
      'version': '0.9',
      'stream': [
        {'type': 'text', 'text': 'a known node'},
        {'type': 'hologram', 'summary': 'three lines changed'},
      ],
    };

    testWidgets('default: the operator-facing debug card, unchanged',
        (tester) async {
      await tester.pumpWidget(const MaterialApp(
        home: Scaffold(body: A2UIRenderer(envelope: unknown)),
      ));
      expect(find.textContaining('unknown v0.9 type: hologram'), findsOneWidget);
    });

    testWidgets('a host can render nothing, deliberately', (tester) async {
      // The gap: returning null from `componentBuilder` means *decline*, which
      // falls through to the amber card. There was no way to say "render
      // nothing" — right for the Explorer, wrong on an end-user's phone.
      await tester.pumpWidget(MaterialApp(
        home: Scaffold(
          body: A2UIRenderer(
            envelope: unknown,
            unknownComponentBuilder: (context, node) =>
                const SizedBox.shrink(),
          ),
        ),
      ));
      expect(find.textContaining('unknown v0.9 type'), findsNothing);
      expect(find.textContaining('hologram'), findsNothing);
      // Positive control: the surface still rendered — the fallback silenced
      // the unknown node, it did not swallow the stream.
      expect(find.text('a known node'), findsOneWidget);
    });

    testWidgets('a host can render its own diagnostic instead', (tester) async {
      // Why a builder and not a strict/lenient flag: "hide it" and "show the
      // debug card" are two points on a line a host may want a third point on.
      await tester.pumpWidget(MaterialApp(
        home: Scaffold(
          body: A2UIRenderer(
            envelope: unknown,
            unknownComponentBuilder: (context, node) =>
                Text('skipped a ${node['type']}'),
          ),
        ),
      ));
      expect(find.text('skipped a hologram'), findsOneWidget);
      expect(find.textContaining('unknown v0.9 type'), findsNothing);
    });

    testWidgets('componentBuilder still wins, and declining still falls to the '
        'fallback', (tester) async {
      await tester.pumpWidget(MaterialApp(
        home: Scaffold(
          body: A2UIRenderer(
            envelope: unknown,
            componentBuilder: (context, node) => node['type'] == 'hologram'
                ? const Text('the host drew it')
                : null,
            unknownComponentBuilder: (context, node) =>
                const Text('the fallback drew it'),
          ),
        ),
      ));
      expect(find.text('the host drew it'), findsOneWidget);
      expect(find.text('the fallback drew it'), findsNothing);
    });

    testWidgets('the seam exists in the v0.8 tree too', (tester) async {
      // Same reasoning as the componentBuilder seam: a host that works against
      // v0.9 and silently keeps the amber card on v0.8 is worse than no hook.
      await tester.pumpWidget(MaterialApp(
        home: Scaffold(
          body: A2UIRenderer(
            envelope: const {
              'version': '0.8',
              'stream': [
                {
                  'Component': {
                    'Hologram': {'summary': 'x'},
                  },
                },
              ],
            },
            unknownComponentBuilder: (context, node) => const Text('hidden'),
          ),
        ),
      ));
      expect(find.text('hidden'), findsOneWidget);
      expect(find.textContaining('unknown v0.8 component kind'), findsNothing);
    });
  });
}
