//! Minimal upstream-agent skeleton for Triton.
//!
//! Triton dispatches to this agent by POSTing the tool's args JSON to
//! `/` with `X-Triton-Tool: <tool>` and `Authorization: Bearer <token>`
//! (see references/01). Outside dev the token is a short-TTL RS256 JWT
//! Triton mints per call (workload→workload auth, no Vault); the agent
//! verifies it against Triton's JWKS. In dev it is the static
//! `dev-token`. The agent verifies the bearer, runs the tool, and
//! returns either raw JSON or a canonical A2UI `surface`
//! (references/02). Triton wraps/builds the response for whatever
//! protocol the original caller used — this agent stays
//! protocol-agnostic.
//!
//! Triton finds this agent by a STATIC map, not Consul: the operator
//! adds `<tool>=<this agent's host:port>` to TRITON_STATIC_UPSTREAMS.
//! There is no self-registration — this is just an HTTP server.
//!
//! Run locally:  cargo run            (dev-token accepted, no issuer)
//! Build to ship: cargo build --release --no-default-features

use std::net::SocketAddr;

use axum::{
    Json, Router,
    extract::State,
    http::{HeaderMap, StatusCode},
    response::IntoResponse,
    routing::{get, post},
};
use serde_json::{Value, json};

#[derive(Clone)]
struct AppState {
    // EDIT: when present, verify real RS256 JWTs against this issuer's
    // JWKS (references/04). Set it to Triton's self-issuer URL — Triton
    // serves discovery at `<issuer>/.well-known/openid-configuration`
    // and keys at `<issuer>/.well-known/jwks.json`. When absent, the
    // dev-token path applies.
    oidc_issuer: Option<String>,
    oidc_audience: Option<String>,
}

#[tokio::main]
async fn main() {
    let state = AppState {
        oidc_issuer: std::env::var("AGENT_OIDC_ISSUER").ok(),
        oidc_audience: std::env::var("AGENT_OIDC_AUDIENCE").ok(),
    };

    let app = Router::new()
        // Triton always POSTs to `/` — it resolved us by tool name from
        // its static map, so there is no per-tool path on our side; the
        // tool rides the `X-Triton-Tool` header (references/01).
        .route("/", post(handle_tool_call))
        .route("/healthz", get(|| async { Json(json!({ "status": "ok" })) }))
        .with_state(state);

    // EDIT: the port the operator names in TRITON_STATIC_UPSTREAMS.
    let port: u16 = std::env::var("AGENT_PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(8080);
    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    eprintln!(r#"{{"kind":"log","level":"info","msg":"agent listening","addr":"{addr}"}}"#);
    axum::serve(listener, app).await.unwrap();
}

async fn handle_tool_call(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(args): Json<Value>,
) -> impl IntoResponse {
    // 1. Verify Triton's bearer before doing any work (references/04).
    let principal = match verify_bearer(&state, &headers).await {
        Ok(sub) => sub,
        Err(reason) => {
            // Never log the token itself (references/09).
            eprintln!(
                r#"{{"kind":"log","level":"warn","msg":"auth rejected","reason":"{reason}"}}"#
            );
            return (StatusCode::UNAUTHORIZED, Json(json!({ "error": "auth" }))).into_response();
        }
    };

    // 2. (OPTIONAL) If a chat adapter declares `identity.kind: upstream`
    // (FR-I-7), Triton dispatches your resolver tool here BEFORE the
    // command tool, naming it in `X-Triton-Tool`. It carries
    // {platform, sender}; return {sub, scopes, tenant} to resolve, or a
    // non-2xx / empty `sub` to refuse (Triton then rejects the inbound
    // 401). Delete this block if you don't use the strategy. See
    // references/01 §upstream + doc/upstream-agent-contract.md §5.
    let tool = headers
        .get("x-triton-tool")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");
    if tool == "resolve_identity" {
        return resolve_identity(&args).into_response();
    }

    // 3. Run the tool. EDIT: this is your domain logic. `args` is the
    // exact object the dispatcher validated against your tool's schema;
    // `tool` (the X-Triton-Tool header above) names which tool to run
    // if this agent serves several.
    let subject = args
        .get("subject")
        .and_then(Value::as_str)
        .unwrap_or("world");
    eprintln!(r#"{{"kind":"log","level":"info","msg":"tool invoked","who":"{principal}"}}"#);

    // 4. Return a canonical A2UI surface (references/02). Triton builds
    // v0.8 / v0.9 / a chat PlatformMessage from this — do NOT emit the
    // versioned wire shape yourself. To return a plain result instead,
    // just `Json(json!({ "answer": 42 }))` and Triton wraps it.
    let surface = json!({
        "surface": {
            "components": [
                { "kind": "text", "value": format!("Hello, {subject}!") },
                { "kind": "narration", "text": "Generated by my-tool-agent." },
                { "kind": "button",
                  "label": "Run again",
                  "tool": "my-tool",
                  "args": { "subject": subject } }
            ]
        }
    });
    (StatusCode::OK, Json(surface)).into_response()
}

/// (OPTIONAL) Resolver tool for the `upstream` identity strategy
/// (FR-I-7). Triton calls this with `{platform, sender}` and expects
/// `{sub, scopes, tenant}` back. EDIT: look the sender up in your own
/// store. Refuse unknown/blocked senders with a non-2xx (or empty
/// `sub`/`tenant`) — Triton rejects the inbound 401 and never dispatches
/// the command tool. See doc/upstream-agent-contract.md §5.
fn resolve_identity(args: &Value) -> impl IntoResponse {
    let platform = args.get("platform").and_then(Value::as_str).unwrap_or("");
    let sender = args.get("sender").and_then(Value::as_str).unwrap_or("");
    if sender.is_empty() {
        return (StatusCode::FORBIDDEN, Json(json!({ "error": "unresolved" }))).into_response();
    }
    // EDIT: real lookup goes here. This skeleton mints a stable subject.
    let _ = platform;
    (
        StatusCode::OK,
        Json(json!({ "sub": sender, "scopes": ["chat"], "tenant": "default" })),
    )
        .into_response()
}

/// Returns the verified subject, or an error reason.
async fn verify_bearer(state: &AppState, headers: &HeaderMap) -> Result<String, String> {
    let bearer = headers
        .get("authorization")
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .ok_or_else(|| "missing bearer".to_string())?;

    match &state.oidc_issuer {
        // Real RS256-JWT path. EDIT: this is a sketch — use the full
        // verify recipe (JWKS discovery + per-kid cache + rotation)
        // from references/04. The issuer is Triton's self-issuer; it
        // serves the verifying keys at `<issuer>/.well-known/jwks.json`.
        Some(issuer) => verify_oidc(issuer, state.oidc_audience.as_deref(), bearer).await,

        // No issuer configured → dev / CI. Accept the literal
        // dev-token, but ONLY when this feature is compiled in.
        // Release builds (`--no-default-features`) reject everything
        // here, so the affordance cannot ship (ADR-10).
        None => {
            #[cfg(feature = "dev-token")]
            {
                if bearer == "dev-token" {
                    return Ok("dev-user".to_string());
                }
                Err("dev-token expected (no issuer configured)".to_string())
            }
            #[cfg(not(feature = "dev-token"))]
            {
                let _ = bearer;
                Err("no OIDC issuer configured and dev-token compiled out".to_string())
            }
        }
    }
}

/// Sketch of the real verification path. Replace with the cached
/// recipe from references/04; this fetches JWKS on every call, which is
/// fine for a skeleton, not for production. Triton mints RS256 tokens,
/// so the algorithm is RS256.
async fn verify_oidc(
    issuer: &str,
    audience: Option<&str>,
    token: &str,
) -> Result<String, String> {
    use jsonwebtoken::{Algorithm, DecodingKey, Validation, decode, decode_header, jwk::JwkSet};

    let discovery: Value = reqwest::get(format!("{issuer}/.well-known/openid-configuration"))
        .await
        .map_err(|e| format!("discovery: {e}"))?
        .json()
        .await
        .map_err(|e| format!("discovery json: {e}"))?;
    let jwks_uri = discovery["jwks_uri"].as_str().ok_or("no jwks_uri")?;
    let jwks: JwkSet = reqwest::get(jwks_uri)
        .await
        .map_err(|e| format!("jwks: {e}"))?
        .json()
        .await
        .map_err(|e| format!("jwks json: {e}"))?;

    let kid = decode_header(token)
        .map_err(|e| format!("header: {e}"))?
        .kid
        .ok_or("token missing kid")?;
    let key = jwks.find(&kid).ok_or("kid not in JWKS")?;
    let decoding = DecodingKey::from_jwk(key).map_err(|e| format!("decoding key: {e}"))?;

    // Triton mints RS256 JWTs for upstream agents, so pin RS256.
    let mut validation = Validation::new(Algorithm::RS256);
    validation.set_issuer(&[issuer]);
    if let Some(aud) = audience {
        validation.set_audience(&[aud]);
    } else {
        validation.validate_aud = false;
    }

    #[derive(serde::Deserialize)]
    struct Claims {
        sub: String,
    }
    let data = decode::<Claims>(token, &decoding, &validation).map_err(|e| format!("verify: {e}"))?;
    Ok(data.claims.sub)
}
